# Generated by Django 3.0.2 on 2020-02-27 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionActividades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colectivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=250)),
                ('imagen_principal', models.CharField(max_length=500)),
                ('imagen_descripcion', models.CharField(max_length=150)),
                ('fundador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundador_colectivo_set', to=settings.AUTH_USER_MODEL)),
                ('lider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lider_colectivo_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RelacionColectivoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_colectivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionColectivos.Colectivo')),
                ('id_integrante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RelacionColectivoActividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificado', models.BooleanField(default=False, null=True)),
                ('id_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionActividades.Actividad')),
                ('id_colectivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionColectivos.Colectivo')),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
