# Generated by Django 3.0.2 on 2020-02-27 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=250)),
                ('imagen_principal', models.CharField(max_length=500)),
                ('imagen_descripcion', models.CharField(max_length=150)),
                ('fundador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundador_comunidad_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RelacionComunidadUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionComunidades.Comunidad')),
                ('id_integrante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
